version: "3"
services:
  db:
    container_name: chimera-db
    image: mysql:8
    platform: linux/arm64
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  api:
    container_name: chimera-api
    build:
      context: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/app/api
    env_file: .env
    tty: true
    stdin_open: true
    depends_on:
      - db
      # - frontend
    command: >
      bash -c "
        bundle config set path vendor/bundle
        bundle install
        bundle exec puma -C config/puma.rb"
  web:
    container_name: chimera-web
    build:
      context: ./web
    ports:
      - 80:80
    depends_on:
      - api
volumes:
  mysql_data:
