require: rubocop-rails

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

  Exclude:
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

#
Style/FrozenStringLiteralComment:
  Enabled: false

# ドキュメント無しを許可
Style/Documentation:
  Enabled: false
