source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.5"

# Use mysql as the database for Active Record
gem "mysql2"

# Use Puma as the app server
gem "puma"

# Use Redis adapter to run Action Cable in production
# gem "redis"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing"

## Add Gem ##

# View Template
gem "slim-rails"

# Json Serializer
gem "active_model_serializers"

# Seed Data
gem "seed-fu"

# env
gem "dotenv-rails"

# auth
gem "jwt"

# postion
gem "acts_as_list"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]

  ## Add Gem ##

  # N+1問題検出
  gem "bullet"

  # RSpec本体
  gem "rspec-rails"

  # テスト用データの生成
  gem 'faker'
  gem "factory_bot_rails"

end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"

  ## Add Gem ##

  gem "pry-byebug"

  # エラー画面の高機能化
  gem "better_errors"
  gem "binding_of_caller"

  # コーディングルールチェック
  gem "rubocop", require: false
  gem "rubocop-rails", require: false

  # ER図の生成
  gem "rails-erd", require: false

  # モデルにテーブル情報のコメントをつける
  gem "annotate"
  # ソースコード中のコメントからドキュメント生成
  gem "yard"
  # yardで生成するドキュメントにannotateのテーブル情報を反映
  gem "kramdown"
  # yardで生成するドキュメントにconcernを反映
  gem "yard-activesupport-concern"

  # 言語ファイル(ja.yml)生成
  gem "i18n_generators"
end
